;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : CB0228DFCB3416ED48B6EC8C4B5CDB659C05E104A8E2E7C2B1720CC97D203324
; Input MD5    : 6907B19D816261D748705E6C7BA9AE1C
; Input CRC32  : BC8E3FD0
; Compiler     : Visual C++

; File Name   : C:\Users\vinic\Downloads\Megaman\MEGAMAN.EXE
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 3A6B9D78 (Mon Jan 22 02:39:52 2001)
; Section 1. (virtual address 00001000)
; Virtual size                  : 00000000 (      0.)
; Section size in file          : 00106E00 (1076736.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default
; OS type         :  MS Windows
; Application type:  32bit

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Execute
AUTO segment para public 'CODE' use32
assume cs:AUTO
;org 401000h
assume es:nothing, ss:nothing, ds:AUTO, fs:nothing, gs:nothing